sudo: false
language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9

script:
 - mvn test
 - mvn package -f ion-java-cli/pom.xml
 - java -jar ion-java-cli/target/ion-java-cli-1.0.jar version
 - git clone git@github.com:amzn/ion-test-driver.git ion-test-driver
 - cd ion-test-driver/amazon/iontest
 - pwd

jobs:
  include:
    stage: report generation
    jdk: openjdk11
    script: mvn test site
    after_success:
      - bash <(curl -s https://codecov.io/bash)
    deploy:
      provider: pages
      local-dir: "./target/site/"
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true # keeps commit history of gh-pages branch
      on:
        branch: master
