name: ion-test-driver

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 9, 10, 11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use java ${{ matrix.node-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.node-version }}
      - run: mvn test




