name: Greetings

on: [pull_request, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: amzn/ion-test-driver

      - name: ls
        run: ls