name: Greetings

on: [pull_request, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: cheqianh/ion-test-driver
          ref: cicd-test

      - name: pwd
        run: pwd

      - name: cd
          run: cd /home/runner/work/ion-test-driver

      - name: pwd
          run: pwd

      - name: ls
          run: ls

      - name: pwd
          run: pwd

      - name: run ion-test-driver
        run: python3 amazon/iontest/ion_test_driver.py